# Generated by Django 4.2 on 2024-02-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bathroom'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathroom_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bathroom Size'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bedroom'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bedroom Size'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='construction_company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Construction Company'),
        ),
        migrations.AlterField(
            model_name='property',
            name='cooling',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cooling'),
        ),
        migrations.AlterField(
            model_name='property',
            name='date_listed',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Listing Data'),
        ),
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Garage Capacity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='interior_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Interior Size'),
        ),
        migrations.AlterField(
            model_name='property',
            name='kitchen',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kitchen Size'),
        ),
        migrations.AlterField(
            model_name='property',
            name='laundry_room_equipment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Laundry Equipments'),
        ),
        migrations.AlterField(
            model_name='property',
            name='living_room_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Living Room Size'),
        ),
        migrations.AlterField(
            model_name='property',
            name='plot_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plot Size'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='roof_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Roof Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('LIVING HOUSE', 'Living House'), ('HOUSE VILLA', 'House Villa'), ('HOUSE APARTMENT', 'House Apartment'), ('OFFICE FLOOR', 'Office Floor')], default='LIVING HOUSE', max_length=20, null=True, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Zip Code'),
        ),
    ]
