# Generated by Django 4.2 on 2024-02-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0002_alter_property_bathroom_alter_property_bathroom_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Property Description'),
        ),
        migrations.AddField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Feature This Property'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Properties/', verbose_name='Add Image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Properties.property')),
            ],
        ),
    ]
